/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comidas;

import javax.swing.JOptionPane;

public class FormularioPedido extends javax.swing.JFrame {
    
    private String nombreComida;
    private double precioComida;
    private String tipoComida;

    /**
     * Creates new form FormularioPedido
     */
    public FormularioPedido(String nombreComida, double precioComida, String tipoComida) {
        initComponents();
        
        this.nombreComida = nombreComida;
        this.precioComida = precioComida;
        this.tipoComida = tipoComida;
        
        btnsTipoPedido.add(rbPC);
        btnsTipoPedido.add(rbPLL);
        
        lblSeleccion.setText("Ha seleccionado " + nombreComida + " - $" + precioComida);
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsTipoPedido = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbPC = new javax.swing.JRadioButton();
        rbPLL = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnRealizarPedido = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADireccion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtADetalles = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmación de pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 368, -1));

        lblSeleccion.setText("Ha seleccionado");
        getContentPane().add(lblSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 368, -1));

        jLabel3.setText("Nombre de quien hace el pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 368, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 368, 28));

        jLabel4.setText("Tipo de pedido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 368, -1));

        rbPC.setText("Para comer");
        rbPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPCActionPerformed(evt);
            }
        });
        getContentPane().add(rbPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, 185, -1));

        rbPLL.setText("Para llevar");
        getContentPane().add(rbPLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 151, 183, -1));

        jLabel5.setText("Ingrese cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, 368, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, 368, 27));

        btnRealizarPedido.setText("REALIZAR PEDIDO");
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 421, 368, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 514, -1, -1));

        jLabel2.setText("Dirección de entrega (opcional)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 241, -1, -1));

        txtADireccion.setColumns(20);
        txtADireccion.setRows(5);
        jScrollPane1.setViewportView(txtADireccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, 368, 49));

        jLabel6.setText("Detalles del pedido (ej. sin cebolla, piña, etc.) (opcional)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, -1, -1));

        txtADetalles.setColumns(20);
        txtADetalles.setRows(5);
        jScrollPane2.setViewportView(txtADetalles);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 348, 368, 55));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recibo.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 120, 430, 430));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recibo.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, 430, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty() || txtCantidad.getText().isEmpty() || (!rbPC.isSelected() && !rbPLL.isSelected())){
        JOptionPane.showMessageDialog(null, "Favor de llenar los campos necesarios", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else{
            int cantidad = Integer.parseInt(txtCantidad.getText());
            if(cantidad<=0){
                JOptionPane.showMessageDialog(null, "La cantidad de productos debe ser mayor a 0", "Error en cantidad", JOptionPane.WARNING_MESSAGE);
            } else{
                String tipocomida = tipoComida;
                String producto = nombreComida;
                String nombre = txtNombre.getText();
                String tipoPedido;
                String direccion = txtADireccion.getText();
                String detalles = txtADetalles.getText();
                if(rbPC.isSelected()){
                    tipoPedido = "Para comer";
                } else{
                    tipoPedido = "Para llevar";
                }
                double total = precioComida * cantidad;

                //validaciones


                //se guarda el pedido en la base de datos
                ConexionBD.guardarPedido(nombre, tipoPedido, direccion, tipocomida, producto, detalles, cantidad, total);
                JOptionPane.showMessageDialog(null, "Pedido realizado con éxito!");
                dispose();
                ventanaprincipal.main(null);
            }
            
        }
        
        
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Se detendrá la transacción", null, JOptionPane.WARNING_MESSAGE);
        dispose();
        ventanaprincipal.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nombreComida = args[0];
                double precio = Double.parseDouble(args[1]);
                String tipoComida = args[2];

                new FormularioPedido(nombreComida, precio, tipoComida).setVisible(true);
            }
        });
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.ButtonGroup btnsTipoPedido;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JRadioButton rbPC;
    private javax.swing.JRadioButton rbPLL;
    private javax.swing.JTextArea txtADetalles;
    private javax.swing.JTextArea txtADireccion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
