/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comidas;

public class tacos extends javax.swing.JFrame {

    /**
     * Creates new form tacos
     */
    public tacos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuHamburguesa = new javax.swing.JLabel();
        lblHamC = new javax.swing.JLabel();
        btnPzPeperoni = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblMenuHamburguesa1 = new javax.swing.JLabel();
        lblHamC1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTcsPastor = new javax.swing.JButton();
        lblHamC2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTcsPastorOrden = new javax.swing.JButton();
        lblHamC3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTcsCarnitas = new javax.swing.JButton();
        lblHamC4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPzCarnitasrOrden = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblHamC5 = new javax.swing.JLabel();
        btnTcsSuadero = new javax.swing.JButton();
        lblHamC6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTcsSuaderoOrden = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblMenuHamburguesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMenuHamburguesa.setText("Menú Pizzas");

        lblHamC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC.setText("- Pizza Pepperoni $99");

        btnPzPeperoni.setText("Comprar");
        btnPzPeperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPzPeperoniActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel3.setText("Elaborada con masa tradicional, salsa de tomate, queso mozzarella, pepperoni");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenuHamburguesa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMenuHamburguesa1.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuHamburguesa1.setText("Menú Tacos");
        getContentPane().add(lblMenuHamburguesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblHamC1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC1.setForeground(new java.awt.Color(255, 255, 255));
        lblHamC1.setText("- 1 Kg Carne al Pastor $219");
        getContentPane().add(lblHamC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Incluye tortillas, limón, piña, cebollin, pepino, rabano, salsas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 439, -1));

        btnTcsPastor.setText("Comprar");
        btnTcsPastor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcsPastorActionPerformed(evt);
            }
        });
        getContentPane().add(btnTcsPastor, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 46, -1, -1));

        lblHamC2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC2.setForeground(new java.awt.Color(255, 255, 255));
        lblHamC2.setText("- 1 Orden de Tacos Carne al Pastor $49");
        getContentPane().add(lblHamC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("4 tacos. Incluye limón, cebollin, piña, pepino, rabano, salsas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 439, -1));

        btnTcsPastorOrden.setText("Comprar");
        btnTcsPastorOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcsPastorOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTcsPastorOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 107, -1, -1));

        lblHamC3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC3.setForeground(new java.awt.Color(255, 255, 255));
        lblHamC3.setText("- 1 Kg de Carnitas $189");
        getContentPane().add(lblHamC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Incluye tortillas, cebolla y cilantro, salsas, limón, nopales asados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, 439, -1));

        btnTcsCarnitas.setText("Comprar");
        btnTcsCarnitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcsCarnitasActionPerformed(evt);
            }
        });
        getContentPane().add(btnTcsCarnitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 168, -1, -1));

        lblHamC4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC4.setForeground(new java.awt.Color(255, 255, 255));
        lblHamC4.setText("- 1 Orden de Tacos de Carnitas $39");
        getContentPane().add(lblHamC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3 tacos. Incluye cebolla y cilantro, salsas, limón, nopales asados");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, 439, -1));

        btnPzCarnitasrOrden.setText("Comprar");
        btnPzCarnitasrOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPzCarnitasrOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnPzCarnitasrOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 229, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Incluye tortillas, cebolla y cilantro, salsas, limón, nopal y cebollin asado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, 439, -1));

        lblHamC5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC5.setForeground(new java.awt.Color(255, 255, 255));
        lblHamC5.setText("- 1 Kg de Suadero $239");
        getContentPane().add(lblHamC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 291, -1, -1));

        btnTcsSuadero.setText("Comprar");
        btnTcsSuadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcsSuaderoActionPerformed(evt);
            }
        });
        getContentPane().add(btnTcsSuadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 290, -1, -1));

        lblHamC6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHamC6.setForeground(new java.awt.Color(255, 255, 255));
        lblHamC6.setText("- 1 Orden de Tacos de Suadero $59");
        getContentPane().add(lblHamC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("5 tacos. Incluye cebolla y cilantro, salsas, limón, nopal y cebollin asado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 439, -1));

        btnTcsSuaderoOrden.setText("Comprar");
        btnTcsSuaderoOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTcsSuaderoOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTcsSuaderoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 351, -1, -1));

        btnRegresar1.setText("Inicio");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tacos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPzPeperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPzPeperoniActionPerformed

    }//GEN-LAST:event_btnPzPeperoniActionPerformed

    private void btnTcsPastorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcsPastorActionPerformed
        // TODO add your handling code here:
        FormularioPedido.main(new String[]{"1kg Pastor", "219", "Tacos"});
        this.dispose();
    }//GEN-LAST:event_btnTcsPastorActionPerformed

    private void btnTcsPastorOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcsPastorOrdenActionPerformed
        // TODO add your handling code here:
        FormularioPedido.main(new String[]{"Orden de Pastor", "49", "Tacos"});
        this.dispose();
    }//GEN-LAST:event_btnTcsPastorOrdenActionPerformed

    private void btnTcsCarnitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcsCarnitasActionPerformed
        // TODO add your handling code here:
        FormularioPedido.main(new String[]{"1kg Carnitas", "189", "Tacos"});
        this.dispose();
    }//GEN-LAST:event_btnTcsCarnitasActionPerformed

    private void btnPzCarnitasrOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPzCarnitasrOrdenActionPerformed
        // TODO add your handling code here:
        FormularioPedido.main(new String[]{"Orden Carnitas", "39", "Tacos"});
        this.dispose();
    }//GEN-LAST:event_btnPzCarnitasrOrdenActionPerformed

    private void btnTcsSuaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcsSuaderoActionPerformed
        // TODO add your handling code here:
        FormularioPedido.main(new String[]{"1kg Suadero", "239", "Tacos"});
        this.dispose();
    }//GEN-LAST:event_btnTcsSuaderoActionPerformed

    private void btnTcsSuaderoOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTcsSuaderoOrdenActionPerformed
        // TODO add your handling code here:
        FormularioPedido.main(new String[]{"Orden Suadero", "59", "Tacos"});
        this.dispose();
    }//GEN-LAST:event_btnTcsSuaderoOrdenActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        ventanaprincipal.main(null);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tacos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tacos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPzCarnitasrOrden;
    private javax.swing.JButton btnPzPeperoni;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnTcsCarnitas;
    private javax.swing.JButton btnTcsPastor;
    private javax.swing.JButton btnTcsPastorOrden;
    private javax.swing.JButton btnTcsSuadero;
    private javax.swing.JButton btnTcsSuaderoOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHamC;
    private javax.swing.JLabel lblHamC1;
    private javax.swing.JLabel lblHamC2;
    private javax.swing.JLabel lblHamC3;
    private javax.swing.JLabel lblHamC4;
    private javax.swing.JLabel lblHamC5;
    private javax.swing.JLabel lblHamC6;
    private javax.swing.JLabel lblMenuHamburguesa;
    private javax.swing.JLabel lblMenuHamburguesa1;
    // End of variables declaration//GEN-END:variables
}
