/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package comidas;


public class ventanaprincipal extends javax.swing.JFrame {

    /** Creates new form ventanaprincipal */
    public ventanaprincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        btnHamburguesas = new javax.swing.JButton();
        lblHamburguesa = new javax.swing.JLabel();
        lblPizza = new javax.swing.JLabel();
        btnPizza = new javax.swing.JButton();
        lblTacos = new javax.swing.JLabel();
        btnTacos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTA DE COMIDAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnHamburguesas.setText("Ver productos");
        btnHamburguesas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHamburguesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesasActionPerformed(evt);
            }
        });
        getContentPane().add(btnHamburguesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 368, -1));

        lblHamburguesa.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        lblHamburguesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburguesa.setText("Hamburguesas");
        getContentPane().add(lblHamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 368, -1));

        lblPizza.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        lblPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPizza.setText("Pizza");
        getContentPane().add(lblPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 368, -1));

        btnPizza.setText("Ver productos");
        btnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 368, -1));

        lblTacos.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        lblTacos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTacos.setText("Tacos");
        getContentPane().add(lblTacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 368, -1));

        btnTacos.setText("Ver productos");
        btnTacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 368, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 610, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHamburguesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesasActionPerformed
        // TODO add your handling code here:
        hamburguesas.main(null);
        this.dispose();
    }//GEN-LAST:event_btnHamburguesasActionPerformed

    private void btnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaActionPerformed
        // TODO add your handling code here:
        pizza.main(null);
        this.dispose();
    }//GEN-LAST:event_btnPizzaActionPerformed

    private void btnTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacosActionPerformed
        // TODO add your handling code here:
        tacos.main(null);
        this.dispose();
    }//GEN-LAST:event_btnTacosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHamburguesas;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnTacos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblHamburguesa;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblTacos;
    // End of variables declaration//GEN-END:variables

}
